server.port: 8080

logging:
  level:
    root: INFO
    com.assignment1: DEBUG

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: root
      password: password
      authentication-database: admin

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: root
      password: password
      authentication-database: admin
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongo1
      port: 27017
      database: library
      username: root
      password: password
      authentication-database: admin